documentation:
- changed-files:
  - any-glob-to-any-file:
    - '**/*.md'

feature:
  - head-branch: ['^feature', 'feature']

fix:
  - head-branch: ['^fix', 'fix']

terraform:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.tf'
