[tools]
opentofu        = "1.8"
pre-commit      = 'latest'
python          = '3.12'
terraform       = "1.8"
terraform-docs  = 'latest'

[settings]
legacy_version_file_disable_tools = ['terraform']
not_found_auto_install            = true
