on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - labeled
      - unlabeled
      - opened
      - reopened
      - synchronize

permissions:
  pull-requests: write
  contents: write

jobs:
  bumper:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v3

      - uses: actions/checkout@v4

      - uses: jwalton/gh-find-current-pr@v1
        id: finder
        with:
          state: all

      - id: bumper
        uses: inetum-poland/action-bumper@v3
        with:
          bump_fail_if_no_level: true
          bump_latest: true
          bump_semver: true

      - uses: marocchino/sticky-pull-request-comment@v2
        if: always() && (steps.bumper.outputs.tag_status != null) && (steps.finder.outputs.pr != null) && (steps.bumper.outputs.skip != true)
        with:
          header: bumper
          number: ${{ steps.finder.outputs.pr }}
          message: ${{ steps.bumper.outputs.tag_status }}

      - uses: marocchino/sticky-pull-request-comment@v2
        if: always() && (steps.bumper.outputs.tag_status == null || steps.bumper.outputs.skip == true)
        with:
          header: bumper
          delete: true

      #TODO(aamkye): Releaser
