name: "Reusable"

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - main

jobs:
  verify:
    name: "Verify"
    uses: Inetum-Poland/.github/.github/workflows/verify.yml@main
    if: github.event.pull_request.draft == false
    secrets: inherit
