name: "Reusable"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - labeled
      - unlabeled
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  assign:
    name: "Assign"
    uses: Inetum-Poland/.github/.github/workflows/assign_label.yml@main
    if: github.event.pull_request.draft == false
