on:
  push:
    branches:
      - main
    tags:
      - 'v?*.*.*'
  pull_request:
    branches:
      - main
    types:
      - labeled
      - unlabeled
      - opened
      - reopened
      - synchronize

jobs:
  tag_bumper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: bumper
        uses: inetum-poland/action-bumper@v2.0.6
        with:
          fail_if_no_bump: true
          bump_semver: true
