name: trufflehog

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  secret_scanning:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: trufflesecurity/trufflehog@main
      with:
        base: ""
        head: ${{ github.ref_name }}
        extra_args: --only-verified
